# _config.yml

# Site settings
title: Local AI Assistant on Raspberry Pi Guide
description: A step-by-step guide to setting up Ollama on a Pi 5 (4GB) and accessing it via a CLI function.

# Theme selection
# Using the 'minimal' theme supported by GitHub Pages
# See: https://github.com/pages-themes/minimal
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # Required plugin for remote themes

# Optional: Uncomment and add your Google Analytics ID if you have one
# google_analytics: UA-XXXXXX-Y
